name: Deploy Edge Functions

on:
  push:
    branches: [main] # deploy on every push to main
  workflow_dispatch: # allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_REF: ${{ secrets.PROJECT_REF }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install the CLI (beta ≥ 2.13.3 supports --use-api)
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.13.3 # or 'latest'

      # OPTIONAL – if you store env vars in Supabase Secrets
      # Uncomment and add your secrets to GitHub and here.
      # - name: Sync Supabase Secrets
      #   run: |
      #     supabase secrets set \
      #       NETO_API_KEY=${{ secrets.NETO_API_KEY }} \
      #       --project-ref $PROJECT_REF

      # Build CLI-v2 compatible folder structure and deploy
      - name: Deploy Edge Functions (Supabase CLI v2)
        run: |
          mkdir -p supabase/functions

          for file in *.js; do
            fn=$(basename "$file" .js)
            # Skip shared helpers
            if [ "$fn" = "sync_utils" ]; then
              continue
            fi

            echo "Preparing function $fn"
            dir="supabase/functions/$fn"
            mkdir -p "$dir"
            # copy entrypoint and shared helpers
            cp "$file" "$dir/index.ts"
            cp sync_utils.js "$dir/sync_utils.js"

            echo "Deploying $fn"
            supabase functions deploy "$fn" \
              --project-ref "$PROJECT_REF" \
              --use-api
          done

          # Explicitly deploy global_sync to ensure it's included
          echo "Preparing function global_sync"
          dir="supabase/functions/global_sync"
          mkdir -p "$dir"
          cp global_sync.js "$dir/index.ts"
          cp sync_utils.js "$dir/sync_utils.js"

          echo "Deploying global_sync"
          supabase functions deploy "global_sync" \
            --project-ref "$PROJECT_REF" \
            --use-api
