name: Neto Sync Cron Job

on:
  schedule:
    - cron: "0 1 * * *" # Run every day at 1:00 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Neto Sync
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/global_sync" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json"
